# Generated by Django 2.0.7 on 2018-08-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaka', '0004_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
