# Generated by Django 2.0.7 on 2018-08-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaka', '0005_auto_20180830_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
