# Generated by Django 2.0.7 on 2018-09-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaka', '0006_auto_20180830_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, upload_to='subjects/%Y/%m/%d'),
        ),
    ]
