# Generated by Django 2.0.7 on 2018-10-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaka', '0008_auto_20180913_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='image',
            field=models.ImageField(blank=True, upload_to='modules'),
        ),
    ]
