# Generated by Django 2.0.7 on 2018-10-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaka', '0009_module_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='image',
            field=models.ImageField(blank=True, upload_to='modules/'),
        ),
    ]
