# Generated by Django 2.0.7 on 2018-10-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaka', '0010_auto_20181002_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
