# Generated by Django 2.0.7 on 2018-10-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaka', '0014_auto_20181002_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='image',
        ),
        migrations.AddField(
            model_name='module',
            name='file',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
