# Generated by Django 2.0.7 on 2018-10-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaka', '0015_auto_20181003_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='file',
            field=models.FileField(blank=True, default=0, upload_to='images'),
            preserve_default=False,
        ),
    ]
