# Generated by Django 2.0.7 on 2018-10-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaka', '0016_auto_20181003_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='file',
            field=models.FileField(upload_to='images'),
        ),
    ]
