# Generated by Django 2.0.7 on 2018-10-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhaka', '0019_auto_20181003_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='module/%Y/%m/%d'),
        ),
    ]
